name:                blocks
version:             0.1.0.0
github:              "githubuser/blocks"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/blocks#readme>

dependencies:
- base >= 4.7 && < 5
- relude
- mtl
- text
- bytestring
- containers
- lens
- servant
- servant-server
- http-media
- aeson
- wai
- wai-extra
- warp

# graphql 
- morpheus-graphql
- morpheus-graphql-core
# - morpheus-graphql-app
# - morpheus-graphql-subscriptions
- file-embed
- websockets
- wai-websockets

library:
  source-dirs: src

executables:
  blocks-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blocks

tests:
  blocks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blocks

default-extensions:
- ApplicativeDo
- BangPatterns
- BinaryLiterals
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- OverloadedStrings
- DerivingStrategies
- DeriveAnyClass
- GeneralizedNewtypeDeriving
- TypeOperators
- DataKinds
- TypeApplications
- MultiParamTypeClasses
- RecordWildCards
- KindSignatures
- TypeFamilies
- LambdaCase
- ScopedTypeVariables
- DerivingVia
- BlockArguments
- NoImplicitPrelude
- DuplicateRecordFields
- NamedFieldPuns
- TemplateHaskell
- PartialTypeSignatures
- ScopedTypeVariables